/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mub_app_HelloJNI */

#ifndef _Included_com_mub_app_HelloJNI
#define _Included_com_mub_app_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mub_app_HelloJNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mub_app_HelloJNI_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mub_app_HelloJNI
 * Method:    incrementNumber
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mub_app_HelloJNI_incrementNumber
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
